title: Sebastiaan Dammann
email: sebastiaandammann@outlook.com
description: >
  Blogging, coding, 3D printing and reviews
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://damsteen.nl" # the base hostname & protocol for your site
twitter_username: sebazzz91
github_username:  sebazzz
linkedin_username: sebastiaandammann

twitter:
  username: sebazzz91

permalink: /blog/:year/:month/:day/:slug

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

feed:
  path: feed.xml

# Build settings
markdown: kramdown
