title: Sebastiaan Dammann
email: www@damsteen.nl
description: >
  Blogging, coding, 3D printing and reviews
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://damsteen.nl" # the base hostname & protocol for your site
twitter_username: sebazzz91
github_username:  sebazzz
linkedin_username: sebastiaandammann
mastodon_username: sebazzz
mastodon_instance: mastodon.nl

twitter:
  username: sebazzz91

permalink: /blog/:year/:month/:day/:slug

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-loading-lazy
  
feed:
  path: feed.xml

# Build settings
markdown: kramdown
